name: Link Check

on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Run markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        # docs at https://git.io/JBaKu
        with:
          config-file: ".github/workflows/link-check-config.json"
          max-depth: 1 # only check readme.md
